### PR TITLE
Separate "pure" Sony repos

### PR DESCRIPTION
**Pull request by pablomh**
Change-Id: I5a2ea8c6baaf486b652d0807896ad0b973793edf

### CODE REVIEW

**Comment by alviteri** [comment]
Vendor are provided by sony...  Don't move them

**Comment by pablomh** [comment]
What about the others?

**Comment by alviteri** [comment]
The others are OK...  Remember this and other one will be merged in next rebase

**Comment by pablomh** [comment]
I'm fine with it (and learning all the different ways that git has of "integrating branches")...

I'll try to include the complete commit in this PR.

**Comment by pablomh** [comment]
Try it now if you like it

**Comment by alviteri** [comment]
perfect but rebase on 1 commit please

**Pull request closed without merging**
